server:
  port: 8082

spring:
  application:
    name: order-service


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8080




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG